import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Datenschutzerklärung" };
const Mail = () => <a className="text-brand-600 underline" href="mailto:kontakt.trendware@gmail.com">kontakt.trendware@gmail.com</a>;

export default function DatenschutzPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <nav className="text-sm text-gray-500 mb-6"><Link href="/">Startseite</Link><span className="mx-2">/</span>Datenschutz</nav>
      <h1 className="font-display text-3xl font-bold text-gray-900 mb-8">Datenschutzerklärung</h1>
      <div className="space-y-7 text-sm leading-relaxed text-gray-600">
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">1. Verantwortliche</h2><p>Chantal Röth, Trendware<br />Im Sennteich 16<br />68189 Mannheim<br />Deutschland<br />E-Mail: <Mail /></p></section>
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">2. Aufruf der Website und Hosting</h2><p>Beim Aufruf der Website werden technisch notwendige Verbindungsdaten verarbeitet, insbesondere IP-Adresse, Zeitpunkt, angeforderte Ressource, Browser- und Geräteinformationen. Die Verarbeitung dient der sicheren und stabilen Bereitstellung nach Art. 6 Abs. 1 lit. f DSGVO.</p><p className="mt-3">Für die technische Bereitstellung können OpenAI Ireland Limited, 1st Floor, The Liffey Trust Centre, 117–126 Sheriff Street Upper, Dublin 1, D01 YC43, Irland, sowie Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, USA, eingesetzt werden. Dabei kann eine Verarbeitung außerhalb des EWR stattfinden. Vor produktiver Aktivierung eines Anbieters werden die erforderlichen datenschutzrechtlichen Vereinbarungen und Übermittlungsgrundlagen geprüft.</p></section>
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">3. Warenkorb</h2><p>Warenkorbinhalte werden technisch notwendig im lokalen Speicher Ihres Browsers gespeichert. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO und § 25 Abs. 2 TDDDG. Sie können die Daten über die Browser-Einstellungen löschen.</p></section>
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">4. Kontakt</h2><p>Bei einer Kontaktaufnahme verarbeiten wir Name, E-Mail-Adresse, Betreff und Nachricht zur Bearbeitung Ihrer Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO bei vertragsbezogenen Anfragen, ansonsten Art. 6 Abs. 1 lit. f DSGVO. Für den E-Mail-Versand kann Resend Inc., USA, eingesetzt werden. Die Daten werden gelöscht, sobald die Anfrage abgeschlossen ist und keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p></section>
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">5. Bestellung und Vertragsabwicklung</h2><p>Bei einer Bestellung verarbeiten wir insbesondere Name, Rechnungs- und Lieferanschrift, E-Mail-Adresse, bestellte Artikel, Zahlungsstatus und gegebenenfalls Telefonnummer. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO. Steuer- und handelsrechtlich relevante Unterlagen werden entsprechend den gesetzlichen Aufbewahrungsfristen gespeichert.</p></section>
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">6. Stripe und PayPal</h2><p>Wenn Sie eine tatsächlich aktivierte Zahlungsart auswählen, werden die für die Zahlung erforderlichen Daten an Stripe Payments Europe Limited, Irland, beziehungsweise PayPal (Europe) S.à r.l. et Cie, S.C.A., Luxemburg, übermittelt. Die Anbieter verarbeiten Zahlungsdaten teilweise in eigener Verantwortlichkeit. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO. Trendware speichert keine vollständigen Karten- oder PayPal-Zugangsdaten.</p></section>
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">7. Lieferanten und Versand</h2><p>Zur Vertragserfüllung können Name, Lieferadresse, Kontaktdaten und Bestellinformationen an den für das konkrete Produkt eingesetzten Lieferanten und Versanddienstleister, insbesondere CJdropshipping, übermittelt werden. Eine Übermittlung außerhalb des EWR erfolgt nur, wenn eine gültige datenschutzrechtliche Grundlage und die erforderlichen Schutzmaßnahmen vorliegen. Produkte bleiben bis zur Prüfung dieser Voraussetzungen nicht bestellbar.</p></section>
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">8. Analyse und Werbung</h2><p>Auf dieser Version der Website werden keine Analyse-, Meta- oder TikTok-Pixel geladen. Solche Dienste werden erst nach Einrichtung einer wirksamen Einwilligungslösung und Aktualisierung dieser Datenschutzerklärung aktiviert.</p></section>
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">9. Ihre Rechte</h2><p>Sie haben im Rahmen der gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie das Recht, erteilte Einwilligungen für die Zukunft zu widerrufen. Anfragen richten Sie an <Mail />. Außerdem können Sie sich bei einer Datenschutzaufsichtsbehörde beschweren.</p></section>
        <section><h2 className="text-lg font-semibold text-gray-900 mb-3">10. Datensicherheit und Änderungen</h2><p>Wir setzen angemessene technische und organisatorische Schutzmaßnahmen ein. Diese Erklärung wird aktualisiert, wenn sich eingesetzte Dienste oder Rechtsgrundlagen ändern.</p></section>
        <p className="text-xs text-gray-500">Stand: September 2026</p>
      </div>
    </div>
  );
}
